<?xml version="1.0" encoding="UTF-8" ?>


<!DOCTYPE DIJAK [
<!ELEMENT DIJAK (IME,PRIIMEK,STEVILKA,ULICA,HISTNA_ST,POSTA)>
<!ELEMENT IME (#PCDATA)>
<!ELEMENT PRIIMEK (#PCDATA)>
<!ELEMENT STEVLKA (#PCDATA)>
<!ELEMENT ULICA (#PCDATA)>
<!ELEMENT HISTNA_ST (#PCDATA)>
<!ELEMENT POSTA (#PCDATA)>
]>



<DIJAK
xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="vaja8.xsd">
    <IME>Jan</IME>
    <PRIIMEK>Milosic</PRIIMEK>
    <STEVILKA>10</STEVILKA>
    <ULICA>Vareja 2a</ULICA>
    <HISTNA_ST>2a</HISTNA_ST>
    <POSTA>2234 Videm pri Ptuju</POSTA>
</DIJAK>